# Generated by Django 2.2.20 on 2021-06-15 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedForReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('companyAddress', models.CharField(max_length=255)),
                ('keyContactName', models.CharField(max_length=255)),
                ('companyNumber', models.CharField(max_length=16)),
                ('solutionName', models.CharField(max_length=255)),
                ('currentStage', models.CharField(max_length=25)),
                ('lastMeetingDate', models.DateField()),
                ('peojectDescribtion', models.CharField(max_length=400)),
                ('clientQuery', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('companyAddress', models.CharField(max_length=255)),
                ('keyContactName', models.CharField(max_length=255)),
                ('companyNumber', models.CharField(max_length=16)),
                ('solutionName', models.CharField(max_length=255)),
                ('currentStage', models.CharField(max_length=25)),
                ('lastMeetingDate', models.DateField()),
                ('peojectDescribtion', models.CharField(max_length=400)),
                ('clientQuery', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acceptedlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('companyAddress', models.CharField(max_length=255)),
                ('keyContactName', models.CharField(max_length=255)),
                ('companyNumber', models.CharField(max_length=16)),
                ('solutionName', models.CharField(max_length=255)),
                ('currentStage', models.CharField(max_length=25)),
                ('lastMeetingDate', models.DateField()),
                ('peojectDescribtion', models.CharField(max_length=400)),
                ('clientQuery', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
