# Generated by Django 2.2.19 on 2021-04-19 15:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0002_higis'),
    ]

    operations = [
        migrations.CreateModel(
            name='editedLayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layer', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
