# Generated by Django 2.2.19 on 2021-05-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=250)),
                ('describtion', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='Project_location',
            new_name='Project_Country',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project_country',
            name='Project_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_locations', to='main.Project_Team'),
        ),
        migrations.AlterField(
            model_name='project_team',
            name='users',
            field=models.ManyToManyField(related_name='project_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
