# Generated by Django 2.2.19 on 2021-05-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210530_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_teams',
        ),
        migrations.AlterField(
            model_name='project_country',
            name='Project_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_locations', to='main.Project_Team'),
        ),
    ]
