# Generated by Django 2.2.20 on 2021-06-02 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210601_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_country',
            name='Project_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_locations', to='main.Project_Team'),
        ),
    ]
