# Generated by Django 2.2.20 on 2021-06-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210606_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_country',
            name='Project_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_locations', to='main.Project_Team'),
        ),
    ]
