# Generated by Django 2.2.16 on 2020-12-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0006_auto_20201227_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(choices=[(models.CharField(max_length=255), models.CharField(max_length=255)), (models.CharField(max_length=255), models.CharField(max_length=255)), (models.CharField(max_length=255), models.CharField(max_length=255)), (models.CharField(max_length=255), models.CharField(max_length=255))], max_length=255),
        ),
    ]
