# Generated by Django 2.2.16 on 2020-12-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0010_auto_20201227_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Learning.Question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='Learning.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Learning.Exam'),
        ),
    ]
