# Generated by Django 2.2.16 on 2020-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0012_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
