# Generated by Django 2.2.16 on 2020-12-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0013_course_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='Learning.Course'),
        ),
    ]
