# Generated by Django 2.2.16 on 2021-01-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0016_auto_20210101_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',)},
        ),
    ]
