# Generated by Django 2.2.16 on 2021-01-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0018_auto_20210102_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-id',)},
        ),
    ]
