# Generated by Django 2.2.16 on 2021-01-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0019_auto_20210102_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
    ]
