# Generated by Django 2.2.16 on 2021-01-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0021_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='exam',
        ),
    ]
