# Generated by Django 2.2.16 on 2021-02-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoleaflet', '0003_hs_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hs',
            name='po',
        ),
    ]
