# Generated by Django 2.2.16 on 2021-04-29 22:55

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0031_merge_20210205_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='editor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_Join_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'permissions': [('Edit_layers', 'Can edit layers')],
            },
        ),
        migrations.CreateModel(
            name='Hige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Higis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('po', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Superviser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='superviser', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_Join_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'permissions': [('Submit Edits', 'Can Review and sibmit  layers')],
            },
        ),
        migrations.CreateModel(
            name='RejectedLyr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('layer', jsonfield.fields.JSONField(default=dict)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_layers', to='mapCustomisation.Editor')),
                ('superviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_layers', to='mapCustomisation.Superviser')),
            ],
        ),
        migrations.CreateModel(
            name='editedLyr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layer', jsonfield.fields.JSONField(default=dict)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_layers', to='mapCustomisation.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedLyr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layer', jsonfield.fields.JSONField(default=dict)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_layers', to='mapCustomisation.Editor')),
                ('superviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_layers', to='mapCustomisation.Superviser')),
            ],
        ),
    ]
