# Generated by Django 2.2.20 on 2021-05-30 15:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapCustomisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedlyr',
            name='layer',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='editedlyr',
            name='layer',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='rejectedlyr',
            name='layer',
            field=jsonfield.fields.JSONField(),
        ),
    ]
